spring:
  application:
    name: realmentor
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:postgresql://localhost:5432/realmentor
    username: postgres
    password: postgres
#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create # none / validate / create

    properties:
      hibernate:
        format_sql: true

    show-sql: true
