spring:
  application:
    name: realmentor
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:h2:mem:realmentor
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # none / validate / create / update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: zavarykin87
    password: pisstybaesxozkza
    test-connection: true
    from: zavarykin87@gmail.com
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.debug]": false
zoom:
  oauth2:
    issuer: https://zoom.us/oauth
    client-id: K8zZCkThTL60qs0zz5jL2g
    client-secret: coDaz8AGAj2V5ibefbjFKV6PVjxI8rxO
    account-id: E5tNFtUxQpijXL_dPfeuxA
    api-url: https://api.zoom.us

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true

jwt:
  secret: kZpzaCGBUXltoydE+SdUpxLnGLu9RGiQW3ef1m+lh5w= # храним тут только на стадии разработки (openssl rand -base64 32)
  expiration: 86400 #24 часа в секундах

logging:
  level:
    org:
      springframework:
        security: DEBUG
